### PR TITLE
Fix to broken soca

### LINKED ISSUE #517: SOCA broken
## Description
several soca tests are broken now after  https://github.com/JCSDA-internal/ufo/pull/695
e.g. `test_soca_3dvar_soca` fails with the following

```
46: At line 555 of file /home/tsluka/work/soca/soca.src/bundle/ufo/src/ufo/GeoVaLs.interface.F90         
46: Fortran runtime error: Index '1' of dimension 1 of array 'geoval' outside of expected range (1:0)
46: [rosealia:39218] *** Process received signal ***                                                     
46: [rosealia:39218] Signal: Segmentation fault (11)    
46: [rosealia:39218] Signal code:  (128)                                                                 
46: [rosealia:39218] Failing at address: (nil)                                                           
46: [rosealia:39218] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x41950)[0x7fd3896d3950]                      
46: [rosealia:39218] [ 1] /usr/lib/x86_64-linux-gnu/libstdc++.so.6(_ZNSo5flushEv+0x10)[0x7fd389b1aa30]
46: [rosealia:39218] [ 2] /opt/jedi_modules/gnu-10.2.0/openmpi-4.0.3/eckit/jcsda-1.11.6.jcsda2/lib/libeckit.so(_ZN5eckit13ChannelBuffer4syncEv+0x49)[0x7fd38b652e89]
46: [rosealia:39218] [ 3] /opt/jedi_modules/gnu-10.2.0/openmpi-4.0.3/eckit/jcsda-1.11.6.jcsda2/lib/libeckit.so(_ZN5eckit13ChannelBuffer5resetEv+0x11)[0x7fd38b653241]
46: [rosealia:39218] [ 4] /opt/jedi_modules/gnu-10.2.0/openmpi-4.0.3/eckit/jcsda-1.11.6.jcsda2/lib/libeckit.so(_ZN5eckit13ChannelBufferD1Ev+0x1b)[0x7fd38b6532bb]
46: [rosealia:39218] [ 5] /opt/jedi_modules/gnu-10.2.0/openmpi-4.0.3/eckit/jcsda-1.11.6.jcsda2/lib/libeckit.so(_ZN5eckit13ChannelBufferD0Ev+0xd)[0x7fd38b6532fd]
46: [rosealia:39218] [ 6] /opt/jedi_modules/gnu-10.2.0/openmpi-4.0.3/eckit/jcsda-1.11.6.jcsda2/lib/libeckit.so(_ZN5eckit7ChannelD1Ev+0x2d)[0x7fd38b65273d]
46: [rosealia:39218] [ 7] /opt/jedi_modules/gnu-10.2.0/openmpi-4.0.3/eckit/jcsda-1.11.6.jcsda2/lib/libeckit.so(_ZN5eckit7ChannelD0Ev+0xd)[0x7fd38b65277d]
46: [rosealia:39218] [ 8] /home/tsluka/work/soca/soca.debug/bin/../lib/liboops.so(_ZNKSt14default_deleteIN5eckit7ChannelEEclEPS1_+0x2c)[0x7fd38a956ce0]
46: [rosealia:39218] [ 9] /home/tsluka/work/soca/soca.debug/bin/../lib/liboops.so(_ZNSt10unique_ptrIN5eckit7ChannelESt14default_deleteIS1_EED1Ev+0x56)[0x7fd38a956bac]
46: [rosealia:39218] [10] /home/tsluka/work/soca/soca.debug/bin/../lib/liboops.so(_ZN4oops7LibOOPSD1Ev+0x58)[0x7fd38a955396]
46: [rosealia:39218] [11] /lib/x86_64-linux-gnu/libc.so.6(__cxa_finalize+0xce)[0x7fd3896d718e]
46: [rosealia:39218] [12] /home/tsluka/work/soca/soca.debug/bin/../lib/liboops.so(+0xc4657)[0x7fd38a904657]
46: [rosealia:39218] *** End of error message ***

```

### PR DESCRIPTION
**Pull request by guillaumevernieres**
## Description
Since we recently imposed the sea-ice state to be 2D (instead of 3D with multiple categories), we can switch from using the currently broken sea ice fraction ufo to the identity. This fixes the currently broken tests that are using the tlm/ad of the sea ice fraction ufo.

## Issue(s) addressed
- closes #517

### CODE REVIEW

File: src/soca/GetValues/soca_getvalues_mod.F90 [hunk 1]
```diff
@@ -181,6 +181,10 @@ subroutine soca_getvalues_fillgeovals(self, geom, fld, t1, t2, locs, geovals)
       call fld%get("chl", fldptr)
       fld3d(isc:iec,jsc:jec,1) = fldptr%val(isc:iec,jsc:jec,1)
 
+    case ("sea_ice_area_fraction")
```
Comment (travissluka) [inline src/soca/GetValues/soca_getvalues_mod.F90:184]: Since we don't have categories anymore, would it be possible to change `sea_ice_category_area_fraction` to `sea_ice_area_fraction` in `soca_fields_mod.F90`, which would mean you wouldn't have to change any lines here in `soca_get_values_mod.F90`?

Comment (guillaumevernieres) [reply src/soca/GetValues/soca_getvalues_mod.F90:184]: It probably would make sense to rename the fields at some point, but I still want to be able to use the sea ice fraction ufo when fixed, and we need `sea_ice_category_area_fraction` for the freeboard/thickness ufo's.

Comment (travissluka) [reply src/soca/GetValues/soca_getvalues_mod.F90:184]: in that case, it might be a good idea to use `SUM(fldptr%val(isc:iec,jsc:jec,:), DIM=3)`. It wont change behavior now, but if we start using categories again we we both know that we'll forget that `sea_ice_area_fraction`  is only pulling from the first category of `cicen` here

Comment (travissluka) [reply src/soca/GetValues/soca_getvalues_mod.F90:184]: ... eh, nevermind, the `soca_getvalues_fillgeovals_ad` section starts getting messy then if you do that

**Review by travissluka — APPROVED** [review]
