### PR TITLE
Completely remove Fortran copy of field data, part 3ish

### LINKED ISSUE #1126: Remove Fortran copy of field values.
Previously, the authoritative copy of the fields was moved into an Atlas Fieldset on the C++ side. However, the fortran `soca_field` contains it's own copy within `val`, so each State/Increment uses 2x the memory it should be using. Some Fortran code has been refactored into C++, but the remaining code that uses the Fortran copy of the fields needs to be refactored.

1. Do a search for `sync_to_atlas()` and `sync_from_atlas()`, all fortran interface functions that use those calls use the fortran internal copy of the fields and needs to be refactored (there are 24 calls to `sync_to_atlas()`, so this is going to be fun)
2. remove those sync functions, and `soca_field::val(:,:,:)`
3. admire the drop in memory usage in celebrate.

Things that need refactoring

- [x] `Model2GeoVaLs`
- [x] `Balance`
- [x] `Soca2Cice`
- [x] `Increment`, `State`, `Fields`

### LINKED ISSUE #1137: segfault in soca VariableChange
## Description

The coupling ctest `test_coupled_hofx3d_fv3_mom6` has been failing recently with a segfault.

Running it locally with some OOPS_DEBUG and OOPS_TRACE, the last print I see is from soca's variable change:
```
...
OOPS_DEBUG[0] VariableChange::changeVar variables after var change: 6 variables: sea_water_salinity, sea_water_potential_temperature, sea_surface_height_above_geoid, sea_water_cell_thickness, eastward_sea_water_velocity, northward_sea_water_velocity
OOPS_DEBUG[0] VariableChange::changeVar SOCA specific post-VADER variable changes.
```

Adding a few more prints of my own, it looks like the segfault is from the `sync_from_atlas` call in the State `updateFields` method. I haven't yet looked deeper.

### To Reproduce:

I'm running on Ubuntu24, gcc13, spack-stack 1.9 ... but this has been present in several environments.

### PR DESCRIPTION
**Pull request by travissluka**
## Description
- closes https://github.com/JCSDA-internal/soca/issues/1126
- closes https://github.com/JCSDA-internal/soca/issues/1137

All remaining places where the Fortran `field%val` was being used have been refactored to directly use the atlas fieldset. This impacts the code in `Increment`, `State`, `Fields`, and `Soca2Cice`.

**There should be no change in answers, but as shown in testing it goes faster and uses less memory.** :tada: 
( and a net removal of 407 lines of code!)

Now that we have moved over to completely using Atlas fieldsets for the `State`/`Increment`, there is additional clean up that could be done (especially regarding metadata and geometry fields) but that is for another day.

## Testing

ctests pass, reference answers are unchanged.

I tested with the 1/4 deg, 1/2 deg minimization on my computer, 24 cores, 20 iterations, and there are no changes in answers

timing / memory with develop
```
OOPS_STATS --------------------------------------------------------------------------------------------
OOPS_STATS ------------------------------------ Timing Statistics -------------------------------------
OOPS_STATS --------------------------------------------------------------------------------------------
OOPS_STATS Name                                                :   total (ms)   count    time/call (ms)
OOPS_STATS oops::Increment::diff                               :     13281.38       3         4427.1259
OOPS_STATS oops::Increment::operator=                          :     12745.08      90          141.6120
OOPS_STATS oops::LinearVariableChange::changeVarAD             :     11579.42      44          263.1685
OOPS_STATS oops::LinearVariableChange::changeVarTL             :      8865.95      44          201.4989
OOPS_STATS oops::LinearVariableChange::changeVarTL             :      8865.95      44          201.4989
OOPS_STATS oops::State::State                                  :     20705.67      12         1725.4722
OOPS_STATS soca::VariableChange::changeVar                     :      4027.01       3         1342.3366
OOPS_STATS util::Timers::Total                                 :    274080.25       1       274080.2542

OOPS_STATS Run end                                  - Runtime:    274.14 sec,  Memory: total:    76.45 Gb, per task: min =     2.89 Gb, max =     3.69 Gb
```

with this PR
```
OOPS_STATS --------------------------------------------------------------------------------------------
OOPS_STATS ------------------------------------ Timing Statistics -------------------------------------
OOPS_STATS --------------------------------------------------------------------------------------------
OOPS_STATS Name                                                :   total (ms)   count    time/call (ms)
OOPS_STATS oops::Increment::diff                               :     10780.44       3         3593.4785
OOPS_STATS oops::Increment::operator=                          :      1464.27      90           16.2697
OOPS_STATS oops::LinearVariableChange::changeVarAD             :      2739.36      44           62.2582
OOPS_STATS oops::LinearVariableChange::changeVarTL             :      1487.92      44           33.8164
OOPS_STATS oops::LinearVariableChange::changeVarTL             :      1487.92      44           33.8164 
OOPS_STATS oops::State::State                                  :     12608.42      12         1050.7013
OOPS_STATS soca::VariableChange::changeVar                     :       413.43       3          137.8085
OOPS_STATS util::Timers::Total                                 :    235221.03       1       235221.0275

OOPS_STATS Run end                                  - Runtime:    235.28 sec,  Memory: total:    50.05 Gb, per task: min =     1.85 Gb, max =     2.90 Gb
```
so 14% faster and 35% less memory

@guillaumevernieres @shlyaeva I'd be curious to see how big the memory impact is for a larger test case using ensemble members (e.g. the LETKF or EnVAR)

jedi-ci-test-select=intel

### CODE REVIEW

File: src/soca/Fields/Fields.cc [hunk 1]
```diff
@@ -207,12 +207,7 @@ void Fields::fromFieldSet(const atlas::FieldSet &fset) {
   util::copyFieldSet(fset, fieldSet_);
 
   for (auto & f : fieldSet_) {
-    if (metadata[f.name()].has("name")) {  // that's weird
-      // THERE IS A BUG IN SOCA, i'm getting fieldsets with one or two fields
-      // (hocn) that have have no metadata even though the rest of the field
```
Comment (kbhargava) [inline src/soca/Fields/Fields.cc:212]: curious what the bug was here

Comment (travissluka) [reply src/soca/Fields/Fields.cc:212]: I think it was something with the "updateFields" call which was removing variables on the fortan side but not removing them on the C++ Atlas Fieldset side. So the atlas fieldsets were building up unused variables that should have been removed during the variable change calls. But now that everything just uses the atlas fieldset, problem solved

**Comment by shlyaeva** [comment]
🎉  I'll get to the review (and hopefully also testing on a high res case) towards the end of this week (but no need to wait for my review if it's ready earlier)

**Review by kbhargava — APPROVED** [review]
Looks good to me. I haven't ran an experiment in a while so I trust your comparisons. :)

**Comment by travissluka** [comment]
> 🎉 I'll get to the review (and hopefully also testing on a high res case) towards the end of this week (but no need to wait for my review if it's ready earlier)

I'll wait until someone on the EMC side can do a test with a high res case, no rush. There were a couple of places where I had to make changes (e.g. changing `toFieldset()` to share fields instead of copy) that should not have made a difference and I couldn't figure out why they were needed to keep answers from changing. So the safety of an extra sanity check will be welcomed.

**Review by shlyaeva — CHANGES_REQUESTED** [review]
I have started reviewing, but haven't reviewed all of the code yet.

I also am running 5-member 0.25deg experiment to compare memory/runtime (I see good changes in letkf!). Unfortunately, I think there's a bug someplace.

Snippet of output log from running EnVar with develop:
```
  0: CostJb: FG-BG
  0:   Valid time: 2021-07-01T00:00:00Z
  0:           sea_ice_area_fraction   min=   -0.798651   max=    0.887274   mean=    0.012367
  0:               sea_ice_thickness   min=    0.000000   max=    0.000000   mean=    0.000000
  0:          sea_ice_snow_thickness   min=    0.000000   max=    0.000000   mean=    0.000000
  0:    snow_ice_surface_temperature   min=    0.000000   max=    0.000000   mean=    0.000000
  0:                 air_temperature   min=    0.000000   max=    0.000000   mean=    0.000000
  0:               bulk_ice_salinity   min=    0.000000   max=    0.000000   mean=    0.000000
  0:              sea_water_salinity   min=   -0.909651   max=    0.351765   mean=    0.000002
  0: sea_water_potential_temperature   min=   -3.925358   max=    3.382241   mean=   -0.002927
  0:  sea_surface_height_above_geoid   min=   -0.038724   max=    0.024073   mean=   -0.000119
  0:        sea_water_cell_thickness   min=    0.000000   max=    0.000000   mean=    0.000000
  0:     ocean_mixed_layer_thickness   min=    0.000000   max=    0.000000   mean=    0.000000
  0:                 sea_water_depth   min=    0.000000   max=    0.000000   mean=    0.000000
  0: CostFunction: Nonlinear J = 220445.635732
  0: OOPS_STATS Variational end                          - Runtime:   110.46 sec,  Local Memory:     1.90 Gb
```
And with this branch:
```
  0: CostJb: FG-BG
  0:   Valid time: 2021-07-01T00:00:00Z
  0:           sea_ice_area_fraction   min=   -0.798651   max=    0.887274   mean=    0.012367
  0:               sea_ice_thickness   min=   -0.000000   max=    0.000000   mean=   -0.000000
  0:          sea_ice_snow_thickness   min=   -0.000000   max=    0.000000   mean=    0.000000
  0:    snow_ice_surface_temperature   min=    0.000000   max=    0.000000   mean=    0.000000
  0:                 air_temperature   min=    0.000000   max=    0.000000   mean=    0.000000
  0:               bulk_ice_salinity   min=    0.000000   max=    0.000000   mean=    0.000000
  0:              sea_water_salinity   min=   -0.909651   max=77008597660148043188051516848840597148668478320250081739882347919495412852191643211583147286958606195079545424975772805674226587963955332572652951943356497323270126883170649247808819839636298060265422848.000000   mean=16957367202475728891577626825028055609821938280924792284389239323344578117770783629386426118938712964638613543994900661595297856385237787777002252292708216949395707990489085012484981218616214028288.000000
  0: sea_water_potential_temperature   min=   -3.925358   max=518265189646136573287931476294616249175124725671191297687214229130607377645751820610464255973296041165448191099564334694541618549907266919569208278910269976772538130645317121874989795554653367823801913902299070424363900875996508230213865290074691821138880419752516255744.000000   mean=67636786550093901176532131630234905456752632162270618593288538827070886417878086024373423664517696999137764061659750679767464063109863615111236375850581140332863691923459520899413268905857091807376212453191771908722835231768689944197064547788628356060398835728384.000000
  0:  sea_surface_height_above_geoid   min=   -0.038724   max=    0.024073   mean=   -0.000119
  0:        sea_water_cell_thickness   min=    0.000000   max=    0.000000   mean=    0.000000
  0:     ocean_mixed_layer_thickness   min=    0.000000   max=    0.000000   mean=    0.000000
  0:                 sea_water_depth   min=    0.000000   max=    0.000000   mean=    0.000000
  0: CostFunction: Nonlinear J = 220445.635732
  0: OOPS_STATS Variational end                          - Runtime:   110.17 sec,  Local Memory:     1.84 Gb
```
(See max values for temp and salinity).
This only shows up in the final cost function for EnVar, I don't see changes in the LETKF output. I haven't explored further yet; I'll take a closer week on Monday to see what may cause this.

**Comment by travissluka** [comment]
@guillaumevernieres @shlyaeva with the EnVAR and LETKF, which, or both, do you have configured to vertically remap the ensemble members onto a common grid? (I'm trying to think of where in the code the bug could be before I dig into it)

**Comment by shlyaeva** [comment]
@guillaumevernieres says we don't remap anymore, so I guess neither.. ("This is done internally to mom6 when outputting history files.") If you can think of other things that could affect it, let me know. I'll also get to debugging it a bit more this pm to see if I can isolate where it's happening.

**Comment by travissluka** [comment]
@shlyaeva okay, next question, were you testing with intel or gnu? I'm guessing there is just uninitialized memory somewhere causing problems, and gnu tends to zero out memory more than intel does. I'll see if I can replicate the bug on my side

**Comment by shlyaeva** [comment]
@travissluka yes, that was intel

**Comment by shlyaeva** [comment]
@travissluka I'll build soca tests and see if it's reproducible in one of the tests.

**Comment by travissluka** [comment]
okay @shlyaeva, it turns out I was being extremely sloppy with the halo regions. oops. There were MANY places where the halos were not being marked as dirty when they should have. I went through the soca code (phew, tired) and ensured halos were being handled correctly.  Assuming the ctests pass, see if this helps with the issue you were seeing

**Comment by shlyaeva** [comment]
🎉  I just reran the last couple of setups I ran that had this issue, and it seems to be resolved! I'll set up a proper clean comparison tomorrow and report back.

**Comment by shlyaeva** [comment]
I've run EnVar and LETKF at 0.25 deg with 80 members, and I don't see the problem reported above anymore!
Some comparisons from running on hera with intel:
EnVar:
dev:
Runtime:    413.73 sec,  Memory: total:   685.13 Gb
this branch:
Runtime:    372.81 sec,  Memory: total:   470.56 Gb

LETKF:
dev:
Runtime:   2305.72 sec,  Memory: total:  4333.59 Gb
this branch:
Runtime:   2264.41 sec,  Memory: total:  1910.04 Gb
🎉 

Not approving quite yet, I see some issues in running our bmatrix preparation task; I suspect it has to do with some changes in increment operations in this PR that are now calling fieldset functions that may not work the same when the variables are different between the increments. Looking into it.

**Comment by travissluka** [comment]
@shlyaeva ah, the "variable exists in rhs but not lhs" error wasn't showing up in the ctests anymore so I switched to using the oops util atlasfieldset functions in several places. Let me know where I need to revert  back (and bonus points if you can modify/create a ctest to trigger that condition!)

**Comment by travissluka** [comment]
> @shlyaeva ah, the "variable exists in rhs but not lhs" error wasn't showing up in the ctests anymore so I switched to using the oops util atlasfieldset functions in several places. Let me know where I need to revert back (and bonus points if you can modify/create a ctest to trigger that condition!)

@shlyaeva I'm going to take an educated guess and say `Increment::operator+=` is the problem, I'll go ahead and revert that section

File: src/soca/Increment/Increment.cc [hunk 2]
```diff
@@ -140,20 +137,30 @@ namespace soca {
...
+      }
+      field.set_dirty(f1.dirty() || f2.dirty());
+    }
   }
 
   // -----------------------------------------------------------------------------
 
   Increment & Increment::operator=(const Increment & rhs) {
     ASSERT(geom_ == rhs.geom_);
+    ASSERT(vars_ == rhs.vars_);
```
Comment (shlyaeva) [inline src/soca/Increment/Increment.cc:180]: It's this new assert that triggers the error in our background error processing. I'll try to change our use so we don't assign increments with different variables.

Comment (shlyaeva) [reply src/soca/Increment/Increment.cc:180]: What we're using it for is creating an Increment that has a subset of variables in the `rhs`. We could just create a copy, and then do `updateFields` on it, but that seems inefficient. What if we added a ctor `Increment(const Increment &, const oops::Variables &)` to handle this case?

Comment (travissluka) [reply src/soca/Increment/Increment.cc:180]: @shlyaeva I'll add in the constructor

Comment (travissluka) [reply src/soca/Increment/Increment.cc:180]: @shlyaeva I added a constructor, give it a try. (it compiles, but is untested in the ctests)

**Review by shlyaeva — APPROVED** [review]
Thanks so much @travissluka, great change!
I've tested as rigorous as I can with low- and high-res gdas tests, all the changes in the output that I saw (minor) are explained and confirm that this code also bugfixes some things (some of the output that was a diagnostic output not used in the cycling).
