### PR TITLE
Make h incr optional

### LINKED ISSUE #794: Remove h from increment
## Description
`h` isn't going to be part of the control variables anytime soon, but it is currently a required increment variable, so a waste of resources.

## Solution
At first glance it seems that the issue might be isolated to the convoluted read in `Fields` and the insitu temperature UFO.

## Alternatives
~Give up and ask @travissluka to fix the "problem" ...~

### LINKED ISSUE #795: [Bug] Interpolation between increment is probably wrong
## Description
The vertical interpolation for increments should use the layer thickness from the geometry, not the increment.

See problem here: 
https://github.com/JCSDA-internal/soca/blob/a532e3e55d70ac5b4b3ff57a59bb3654d77d3dc6/src/soca/Increment/soca_increment_mod.F90#L326

### PR DESCRIPTION
**Pull request by guillaumevernieres**
## Description
What the title says ...

### Issue(s) addressed
- fixes #795 
- fixes #794 

## Testing
Removed the `hocn` increment in :
- `3dvar_soca.yml` , same results.
- `3dvarlowres_soca.yml` ... not the same results as develop ... Needs attention. 

## Dependencies
- waiting on JCSDA/ufo/pull/2190

### CODE REVIEW

**Comment by guillaumevernieres** [comment]
Dear reviewers, 
FYI: The UFO PR was merged ... If that was stopping you from reviewing :)

**Comment by liuxiao37k** [comment]
> Dear reviewers,
> FYI: The UFO PR was merged ... If that was stopping you from reviewing :)

Okay, okay, I am building now... :joy:

**Review by kbhargava — APPROVED** [review]

File: src/soca/Fields/soca_fields_mod.F90 [hunk 1]
```diff
@@ -811,7 +809,7 @@ subroutine soca_fields_read(self, f_conf, vdate)
 
   ! iread = 1 (state) or 3 (increment): Read restart file
   if ((iread==1).or.(iread==3)) then
-
+    if (iread==1) call self%get("hocn", hocn)
```
Comment (travissluka) [inline src/soca/Fields/soca_fields_mod.F90]: because I hate the `iread==` parts.... can you just use `self%has` and read in `hocn` if it exists? I plan (someday) to rip out those error prone `iread` parts

**Review by liuxiao37k — APPROVED** [review]
I tested on Orion with _Intel_, ctests passed except the known stubborn seven. I didn't check if all unnecessary `hocn` has been removed from yamls.

**Review by ShastriPaturi — APPROVED** [review]
I was able to test on orion.

**Review by kbhargava — APPROVED** [review]
All tests pass on orion except the ones that usually fail.
