### PR TITLE
Bugfix for Soca2Cice: use correct mask to mask out points on land

### LINKED ISSUE #1160: Soca2Cice is using incorrect mask to remove ice over land
## Description

Soca2Cice is effectively removing ice close to the coast, especially evident in the Canadian Archipelago in winter. This is because it's using umask from the restart files to remove ice "over land" (except it turns out it's not really over land).

I'm working on a fix.

### PR DESCRIPTION
**Pull request by shlyaeva**
## Description

Soca2Cice on develop is effectively removing ice close to the coast, especially evident in the Canadian Archipelago in winter. This is because it's using umask from the restart files to remove ice "over land" (except it turns out it's not really over land).

This is fixing it by using the mask from the geometry to mask out points on land. Some code that is no longer used is removed.

### Issue(s) addressed

Fixes #1160 

Test from a winter high-res experiment:
CICE restart background:
bg
Raw SOCA increment:
soca_inc
CICE restart analysis (result of ConvertState using Soca2Cice and increment above) - CICE restart background, on develop (note coastlines pattern):
restan_restbg_diff_dev
CICE restart analysis - CICE restart background, with this branch:
restan_restbg_diff_fix

### CODE REVIEW

**Comment by shlyaeva** [comment]
Note: the `convertstate_soca2cice` test output has changed slightly, but the output files show no difference. I don't understand why the test output in the log has changed.

**Review by guillaumevernieres — APPROVED** [review]
I'm a bugvloper.
Thanks @shlyaeva !

File: src/soca/VariableChange/Soca2Cice/soca_ciceutils_mod.F90 [hunk 1]
```diff
@@ -301,25 +277,9 @@ subroutine soca_ciceutils_read(self, geom)
...
-           call aggregate_area (self%aicen(i,j,:), &
-                                self%aice(i,j), aice0)
-           self%agg%lon(cnt) = geom%lon(i,j)
-           self%agg%lat(cnt) = geom%lat(i,j)
-           self%agg%aice(cnt) = self%aice(i,j)
-           self%agg%ij(1,cnt) = i
-           self%agg%ij(2,cnt) = j
-           cnt = cnt + 1
-        end if
+       call aggregate_area(self%aicen(i,j,:), self%aice(i,j), aice0)
```
Comment (shlyaeva) [inline src/soca/VariableChange/Soca2Cice/soca_ciceutils_mod.F90:282]: I understand why the test reference changed. This computation (total ice concentration) used to happen only for the values that were not masked by the incorrect mask, and now it's happening for all gridpoints. The result of this computation is used in shuffling. On develop, incorrectly, some points that were eligible for shuffling did not have correct values. That's now resolved.

Tested this hypothesis by using develop and moving this call outside of the if statement; the test reference changed to what is used in this PR.

**Review by Dooruk — APPROVED** [review]

**Comment by Dooruk** [comment]
So, I tested my sandbox 3dvar diffusion setup with 5 different JEDI builds, with the same adt, insitu, sst, and sea-ice (north & south) observations. Essentially everything is identical except the JEDI builds from:

February 
March
April
May x2 (latest build today)

My `norm reduction`s or `residual norms` in OOPS logs are identical between these builds and I see @shlyaeva made quite some changes to seaice part and I see test references are changing. Are my results expected?

**Edit:** After thinking for more than 10 seconds, I guess most if not all changes are in the soca2cice part?

**Comment by shlyaeva** [comment]
@Dooruk since soca2cice is only used in postprocessing after Var, I wouldn't expect the norm reduction in var to be affected by this, which is consistent with your runs.

**Comment by Dooruk** [comment]
> @Dooruk since soca2cice is only used in postprocessing after Var, I wouldn't expect the norm reduction in var to be affected by this, which is consistent with your runs.

Thanks, that occurred to me as I pressed send. I guess all of your changes have been pertaining the postprocessing part then, right? Over the past few months*

**Comment by shlyaeva** [comment]
@Dooruk yes
